"""Deleted 4 one-to-many tables and added enum columns instead of them

Revision ID: 125980b4a0a4
Revises: 2348eee43c8c
Create Date: 2022-08-26 13:55:46.424471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125980b4a0a4'
down_revision = '2348eee43c8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('forms_living_condition_id_fkey', 'forms', type_='foreignkey')
    op.drop_constraint('forms_origin_id_fkey', 'forms', type_='foreignkey')
    op.drop_constraint('forms_education_id_fkey', 'forms', type_='foreignkey')
    op.drop_constraint('forms_working_style_id_fkey', 'forms', type_='foreignkey')

    op.drop_table('working_styles')
    op.drop_table('educations')
    op.drop_table('origins')
    op.drop_table('living_conditions')

    op.drop_column('forms', 'living_condition_id')
    op.drop_column('forms', 'working_style_id')
    op.drop_column('forms', 'origin_id')
    op.drop_column('forms', 'education_id')

    op.execute("create type livingconditionsenum as enum ('FLAT', 'HOUSE');")
    op.execute("create type educationsenum as enum ('SECONDARY', 'SECONDARY_SPECIAL', 'BACHELOR', 'MASTER');")
    op.execute("create type originsenum as enum ('FAMILIAR', 'TELEGRAM', 'INSTAGRAM', 'FACEBOOK');")
    op.execute("create type workingstylesenum as enum ('COLLECTIVE', 'INDIVIDUAL');")

    op.add_column('forms', sa.Column('living_conditions', sa.Enum('flat', 'house', name='livingconditionsenum'), nullable=False))
    op.add_column('forms', sa.Column('education', sa.Enum('secondary', 'secondary_special', 'bachelor', 'master', name='educationsenum'), nullable=False))
    op.add_column('forms', sa.Column('origin', sa.Enum('familiar', 'telegram', 'instagram', 'facebook', name='originsenum'), nullable=False))
    op.add_column('forms', sa.Column('working_style', sa.Enum('collective', 'individual', name='workingstylesenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('drop type livingconditionsenum;')
    op.execute('drop type educationsenum;')
    op.execute('drop type originsenum;')
    op.execute('drop type workingstylesenum;')
    op.add_column('forms', sa.Column('education_id', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('forms', sa.Column('origin_id', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('forms', sa.Column('working_style_id', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('forms', sa.Column('living_condition_id', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('forms_working_style_id_fkey', 'forms', 'working_styles', ['working_style_id'], ['style_id'], ondelete='RESTRICT')
    op.create_foreign_key('forms_education_id_fkey', 'forms', 'educations', ['education_id'], ['education_id'], ondelete='RESTRICT')
    op.create_foreign_key('forms_origin_id_fkey', 'forms', 'origins', ['origin_id'], ['origin_id'], ondelete='RESTRICT')
    op.create_foreign_key('forms_living_condition_id_fkey', 'forms', 'living_conditions', ['living_condition_id'], ['condition_id'], ondelete='RESTRICT')
    op.drop_column('forms', 'working_style')
    op.drop_column('forms', 'origin')
    op.drop_column('forms', 'education')
    op.drop_column('forms', 'living_conditions')
    op.create_table('living_conditions',
    sa.Column('condition_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('condition_title', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('condition__title_uz', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('condition_id', name='living_conditions_pkey'),
    sa.UniqueConstraint('condition_title', name='living_conditions_condition_title_key')
    )
    op.create_table('origins',
    sa.Column('origin_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('origin_title', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('origin_title_uz', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('origin_id', name='origins_pkey'),
    sa.UniqueConstraint('origin_title', name='origins_origin_title_key')
    )
    op.create_table('educations',
    sa.Column('education_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('degree_title', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('degree_title_uz', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('education_id', name='educations_pkey'),
    sa.UniqueConstraint('degree_title', name='educations_degree_title_key')
    )
    op.create_table('working_styles',
    sa.Column('style_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('style_title', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('style_title_uz', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('style_id', name='working_styles_pkey'),
    sa.UniqueConstraint('style_title', name='working_styles_style_title_key')
    )
    # ### end Alembic commands ###
