"""Added unique constraint to 4 one-to-many tables' columns

Revision ID: 2348eee43c8c
Revises: 68325e5795c9
Create Date: 2022-08-24 16:50:09.911002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2348eee43c8c'
down_revision = '68325e5795c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'educations', ['degree_title'])
    op.create_unique_constraint(None, 'living_conditions', ['condition_title'])
    op.create_unique_constraint(None, 'origins', ['origin_title'])
    op.create_unique_constraint(None, 'working_styles', ['style_title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'working_styles', type_='unique')
    op.drop_constraint(None, 'origins', type_='unique')
    op.drop_constraint(None, 'living_conditions', type_='unique')
    op.drop_constraint(None, 'educations', type_='unique')
    # ### end Alembic commands ###
