"""Added new columns to 4 one-to-many tables

Revision ID: 68325e5795c9
Revises: a31c36898411
Create Date: 2022-08-24 16:18:01.688915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68325e5795c9'
down_revision = 'a31c36898411'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educations', sa.Column('degree_title', sa.VARCHAR(length=64), nullable=False))
    op.add_column('educations', sa.Column('degree_title_uz', sa.VARCHAR(length=64), nullable=False))
    op.drop_column('educations', 'degree')
    op.add_column('living_conditions', sa.Column('condition_title', sa.VARCHAR(length=32), nullable=False))
    op.add_column('living_conditions', sa.Column('condition__title_uz', sa.VARCHAR(length=32), nullable=False))
    op.drop_column('living_conditions', 'condition')
    op.add_column('origins', sa.Column('origin_title', sa.VARCHAR(length=32), nullable=False))
    op.add_column('origins', sa.Column('origin_title_uz', sa.VARCHAR(length=32), nullable=False))
    op.drop_column('origins', 'origin')
    op.add_column('working_styles', sa.Column('style_title', sa.VARCHAR(length=32), nullable=False))
    op.add_column('working_styles', sa.Column('style_title_uz', sa.VARCHAR(length=32), nullable=False))
    op.drop_column('working_styles', 'working_style')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('working_styles', sa.Column('working_style', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('working_styles', 'style_title_uz')
    op.drop_column('working_styles', 'style_title')
    op.add_column('origins', sa.Column('origin', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('origins', 'origin_title_uz')
    op.drop_column('origins', 'origin_title')
    op.add_column('living_conditions', sa.Column('condition', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('living_conditions', 'condition__title_uz')
    op.drop_column('living_conditions', 'condition_title')
    op.add_column('educations', sa.Column('degree', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('educations', 'degree_title_uz')
    op.drop_column('educations', 'degree_title')
    # ### end Alembic commands ###
