"""Changed column 'username' from table 'users' to nullable

Revision ID: ff4f29e81654
Revises: ff849187cac8
Create Date: 2022-08-29 12:11:05.299080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4f29e81654'
down_revision = 'ff849187cac8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universities', 'started_at')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('worked_companies', 'finished_at',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worked_companies', 'finished_at',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('universities', sa.Column('started_at', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
