"""Added 'OTHER' constant to OriginsEnum

Revision ID: ff849187cac8
Revises: 125980b4a0a4
Create Date: 2022-08-26 15:37:39.973530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff849187cac8'
down_revision = '125980b4a0a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("alter type originsenum add value 'OTHER' after 'FACEBOOK';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("drop type originsenum;")
    op.execute("create type originsenum as enum ('FAMILIAR', 'TELEGRAM', 'INSTAGRAM', 'FACEBOOK');")
    # ### end Alembic commands ###
